name: "Delete untagged image from ghcr.io"
inputs:
  images:
    required: true
  delete_image_token:
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # Deleting images with no tag
        gh auth login --with-token <<<"${{ inputs.delete_image_token }}"
        for image in ${{ inputs.images }} ; do
          versions_path="https://api.github.com/orgs/nethesis/packages/container/${image}/versions"
          for version_id in $(gh api --paginate -q ".[] | select(.metadata.container.tags == []) | .id" ${versions_path} | tr '\n' ' '); do
            gh api --input /dev/null -X DELETE "${versions_path}/${version_id}"
            echo "::notice::DELETE ${image}/${version_id}"
          done
        done
