name: "Clean API JSON Schema docs"

on:
  workflow_call:

permissions:
  contents: write

jobs:
  clean-apidoc:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: cleanup
        run: |
          REMOTE_BRANCH="apidoc-${{ github.event.ref }}"
          if git fetch -q origin "${REMOTE_BRANCH}"; then
            git push -f origin ":${REMOTE_BRANCH}"
          fi
