name: "Publish images"

on:
  workflow_call:
    inputs:
      runner-version:
        description: 'The version of the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
    secrets:
      netrcb64:
        description: "Netrc Base64-encoded file content for authenticated downloads. Overrides netrc secret."
        required: false

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish_images:
    name: 'Publish module images'
    runs-on: ${{ inputs.runner-version }}
    env:
      REPOBASE: ghcr.io/${{ github.repository_owner }}
      IMAGETAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: ui/node_modules
          key: "yarn-${{ hashFiles('ui/yarn.lock') }}"
      - id: build
        run: |
          # Try NethServer mirrors before going to docker.io to avoid rate-limits
          mkdir -vp /etc/containers/registries.conf.d
          cat - >/etc/containers/registries.conf.d/800-nethserver.conf <<'EOF'
          [[registry]]
          location = "docker.io"
          [[registry.mirror]]
          location = "ghcr.io/nethserver/docker.io"
          EOF
          # Write .netrc file with the secret contents:
          ( umask 077 ; base64 -d <<<"${{ secrets.netrcb64 }}" >~/.netrc || : ; )
          # Build the module images
          REPOBASE=${REPOBASE,,}
          export REPOBASE
          bash build-images.sh
      - id: publish
        run: |
          # Publish the branch
          trap 'buildah logout ghcr.io' EXIT
          buildah login -u ${{ github.actor }} --password-stdin ghcr.io <<<"${{ secrets.GITHUB_TOKEN }}"
          images=(${{ steps.build.outputs.images }})
          urls=""
          for image in "${images[@]}" ; do
            buildah push $image docker://${image}:${IMAGETAG:?}
            if [[ "${IMAGETAG}" == "main" || "${IMAGETAG}" == "master" ]]; then
                buildah push $image docker://${image}:latest
            fi
            urls="${image}:${IMAGETAG} "$'\n'"${urls}"
          done
          echo "::notice title=Image URLs::${urls}"
