name: "Analyze images with Trivy"

on:
  workflow_call:
    inputs:
      images:
        description: "List of images to analyze"
        required: true
        type: string
      update_dependencies_graph:
        description: "Update GitHub Dependency Graph"
        type: boolean
        default: true
      vulnerability_scan:
        description: "Run vulnerability scan"
        type: boolean
        default: true
      severity:
        description: "Severities of vulnerabilities to scan for and display"
        required: false
        type: string
        default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

permissions:
  security-events: write

jobs:
  scan_images:
    name: "Scan images"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(inputs.images) }}
    steps:
      - name: Run vulnerability scanner
        if: ${{inputs.vulnerability_scan == true}}
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ matrix.image }}
          severity: ${{ inputs.severity }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          limit-severities-for-sarif: true
      - name: Upload scan results to GitHub Security tab
        if: ${{inputs.vulnerability_scan == true}}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Update GitHub Dependency Graph
        if: ${{inputs.update_dependencies_graph == true}}
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ matrix.image }}
          format: github
          output: sbom.github.json
          github-pat: ${{ secrets.GITHUB_TOKEN }}
