name: "Analyze images with Trivy"

on:
  workflow_call:
    inputs:
      images:
        description: "List of images to analyze"
        required: true
        type: string
      scan_module_ui:
        description: "Scan module UI"
        type: boolean
        default: true
      scan_module_imageroot:
        description: "Scan module imageroot"
        type: boolean
        default: true
      generate_sbom:
        description: "Generate SBOM"
        type: boolean
        default: true
      update_dependencies_graph:
        description: "Update GitHub Dependency Graph"
        type: boolean
        default: true
      vulnerability_scan:
        description: "Run vulnerability scan"
        type: boolean
        default: true
      severity:
        description: "Severities of vulnerabilities to scan for and display"
        required: false
        type: string
        default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
      ui_path:
        description: "Path to UI directory. The default value './ui' is suitable for all NS8 modules, while the core needs to pass './core/ui' instead."
        type: string
        default: "./ui"
      imageroot_path:
        description: "Path to imageroot directory. The default value './imageroot' is suitable for all NS8 modules, while the core needs to pass './core/imageroot' instead."
        type: string
        default: "./imageroot"

jobs:
  scan_ui_imageroot:
    name: "Scan module UI and imageroot"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "ui"
            path: ${{ inputs.ui_path }}
            scan_enabled: ${{ inputs.scan_module_ui }}
          - name: "imageroot"
            path: ${{ inputs.imageroot_path }}
            scan_enabled: ${{ inputs.scan_module_imageroot }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}
      - name: Run vulnerability scanner
        if: ${{matrix.scan_enabled == true && inputs.vulnerability_scan == true}}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          scan-ref: ${{ matrix.path }}
          severity: ${{ inputs.severity }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          limit-severities-for-sarif: true
      - name: Upload scan results to GitHub Security tab
        if: ${{matrix.scan_enabled == true && inputs.vulnerability_scan == true}}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Update GitHub Dependency Graph
        if: ${{matrix.scan_enabled == true && inputs.update_dependencies_graph == true}}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          scan-ref: ${{ matrix.path }}
          format: github
          output: sbom.github.json
          github-pat: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate CycloneDX SBOM
        if: ${{matrix.scan_enabled == true && inputs.generate_sbom == true}}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          scan-ref: ${{ matrix.path }}
          format: cyclonedx
          output: ${{ matrix.name }}.cdx.json
      - name: Upload CycloneDX SBOM
        if: ${{matrix.scan_enabled == true && inputs.generate_sbom == true}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-cyclonedx-sbom
          path: ${{ matrix.name }}.cdx.json
      - name: Upload SBOM to GitHub Release
        if: ${{matrix.scan_enabled == true && inputs.generate_sbom == true }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.workflow_run.head_branch || github.ref_name }}
        run: |
          # Check if this tag has a corresponding GitHub release
          if gh release view "$TAG_NAME" --repo ${{ github.repository }} &>/dev/null; then
            echo "Release for tag $TAG_NAME found. Uploading SBOM file..."
            gh release upload "$TAG_NAME" "${{ matrix.name }}.cdx.json" \
              --clobber --repo ${{ github.repository }}
          else
            echo "No release found for tag $TAG_NAME. Skipping SBOM upload."
          fi

  scan_images:
    name: "Scan images"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(inputs.images) }}
    steps:
      - name: Run vulnerability scanner
        if: ${{inputs.vulnerability_scan == true}}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ matrix.image }}
          severity: ${{ inputs.severity }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          limit-severities-for-sarif: true
      - name: Upload scan results to GitHub Security tab
        if: ${{inputs.vulnerability_scan == true}}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Update GitHub Dependency Graph
        if: ${{inputs.update_dependencies_graph == true}}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ matrix.image }}
          format: github
          output: sbom.github.json
          github-pat: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate CycloneDX SBOM
        if: ${{inputs.generate_sbom == true}}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ matrix.image }}
          format: cyclonedx
          output: sbom-${{ github.run_id }}-${{ github.run_attempt }}.cdx.json
      - name: Set safe filename
        if: ${{inputs.generate_sbom == true}}
        id: safe-filename
        run: |
          SAFE_NAME=$(echo "${{ matrix.image }}" | sed 's/[^a-zA-Z0-9]/-/g')
          echo "safe_name=${SAFE_NAME}" >> $GITHUB_OUTPUT
      - name: Upload CycloneDX SBOM
        if: ${{inputs.generate_sbom == true}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.safe-filename.outputs.safe_name }}-cyclonedx-sbom
          path: sbom-${{ github.run_id }}-${{ github.run_attempt }}.cdx.json
      - name: Upload SBOM to GitHub Release
        if: ${{inputs.generate_sbom == true }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME:  ${{ github.event.workflow_run.head_branch || github.ref_name }}
          FILE_PATH: sbom-${{ github.run_id }}-${{ github.run_attempt }}.cdx.json
        run: |
          # rename the file to the a safe name
          mv $FILE_PATH "${{ steps.safe-filename.outputs.safe_name }}.cdx.json"
          # Check if this tag has a corresponding GitHub release
          if gh release view "$TAG_NAME" --repo ${{ github.repository }} &>/dev/null; then
            echo "Release for tag $TAG_NAME found. Uploading SBOM file..."
            gh release upload "$TAG_NAME" \
              "${{ steps.safe-filename.outputs.safe_name }}.cdx.json" \
              --clobber --repo ${{ github.repository }}
          else
            echo "No release found for tag $TAG_NAME. Skipping SBOM upload."
          fi
