name: Test module

on:
  workflow_call:
    inputs:
      debug_shell:
        description: "Debug shell"
        required: false
        type: boolean
        default: false
    secrets:
      do_token:
        required: true

jobs:
  module:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == '' }}
    uses: ./.github/workflows/module-info.yml

  chooser:
    runs-on: ubuntu-latest
    outputs:
      node_a: ${{ steps.pick.outputs.node_a }}
      node_b: ${{ steps.pick.outputs.node_b }}
    steps:
      - id: pick
        run: |
          if (( $GITHUB_RUN_NUMBER % 2 )); then
            echo "node_a=rl1" >> "$GITHUB_OUTPUT"
            echo "node_b=dn1" >> "$GITHUB_OUTPUT"
          else
            echo "node_a=dn1" >> "$GITHUB_OUTPUT"
            echo "node_b=rl1" >> "$GITHUB_OUTPUT"
          fi

  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      run_ui_tests: ${{ steps.changes.outputs.run_ui_tests }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          fetch-depth: 2
      - id: changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -qE '^ui/|^build-images\.sh$'; then
            echo "run_ui_tests=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_ui_tests=false" >> "$GITHUB_OUTPUT"
          fi

  run_tests:
    needs: [module, chooser, detect_changes]
    strategy:
      fail-fast: false
      matrix:
        scenario: [install, update]
    uses: ./.github/workflows/test-on-digitalocean-infra.yml
    with:
      coremodules: ${{ matrix.scenario == 'install' && format('ghcr.io/{0}/{1}:{2}', needs.module.outputs.owner, needs.module.outputs.name, needs.module.outputs.tag) || '' }}
      leader_nodes: >-
        ${{
          matrix.scenario == 'install'
          && needs.chooser.outputs.node_a
          || needs.chooser.outputs.node_b
        }}
      args: ${{ format('ghcr.io/{0}/{1}:{2} -v SCENARIO:{3}', needs.module.outputs.owner, needs.module.outputs.name, needs.module.outputs.tag, matrix.scenario) }}
      repo_ref: ${{ needs.module.outputs.sha }}
      run_ui_tests: ${{ needs.detect_changes.outputs.run_ui_tests == 'true' }}
      debug_shell: ${{ inputs.debug_shell }}
    secrets:
      do_token: ${{ secrets.do_token }}
